"""
stubs.py

Mock data for development and offline fallback.
All data structures match the contracts from src/analysis/*.py.
Excluded from coverage: see pyproject.toml [tool.coverage.run] omit setting.
"""

from __future__ import annotations

from typing import Any

import pandas as pd

STUB_DAILY_REPORT: dict[str, Any] = {
    "report_date": "2026-04-15",
    "week_number": 3,
    "lineup": {
        "C": "p_realmuto",
        "1B": "p_goldschmidt",
        "2B": "p_edman",
        "3B": "p_devers",
        "SS": "p_tatis",
        "OF1": "p_judge",
        "OF2": "p_trout",
        "OF3": "p_soto",
        "Util1": "p_betts",
        "Util2": "p_acuna",
        "SP1": "p_degrom",
        "SP2": "p_scherzer",
        "RP1": "p_hader",
        "RP2": "p_clase",
        "P1": "p_gausman",
        "P2": "p_verlander",
    },
    "adds": [
        {
            "add_player_id": "p_callup1",
            "drop_player_id": "p_bench1",
            "reason": (
                "Adds value in: K, SV+H · "
                "K: trailing (flippable) (gap 18) · SV+H: toss-up (gap 2) · "
                "Called up 2 days ago from AAA Nashville · "
                "Steamer: .271/.792 OPS, 5 SB projected rest-of-season"
            ),
            "score": 8.4,
            "categories_improved": ["k", "sv_h"],
            "add_position": "OF",
            "add_streak": "🔥 Hot",
            "add_callup_note": "Called up 2 days ago from AAA Nashville",
            "add_proj": {
                "proj_avg": 0.271,
                "proj_ops": 0.792,
                "proj_hr": 12.0,
                "proj_sb": 18.0,
                "proj_h": 95.0,
                "proj_bb": 32.0,
                "proj_k": None,
                "proj_w": None,
                "proj_sv_h": None,
                "proj_whip": None,
                "proj_k_bb": None,
                "source": "Steamer",
            },
            "drop_position": "OF/1B",
            "drop_streak": "—",
            "drop_proj": {
                "proj_avg": 0.261,
                "proj_ops": 0.844,
                "proj_hr": 22.0,
                "proj_sb": 3.0,
                "proj_h": 88.0,
                "proj_bb": 38.0,
                "proj_k": None,
                "proj_w": None,
                "proj_sv_h": None,
                "proj_whip": None,
                "proj_k_bb": None,
                "source": "Steamer",
            },
            "matchup_context": "K: trailing (flippable) (gap 18) · SV+H: toss-up (gap 2)",
        },
        {
            "add_player_id": "p_wire2",
            "drop_player_id": "p_verlander",
            "reason": (
                "Adds value in: K, W, WHIP · "
                "K: trailing (flippable) (gap 22) · "
                "Currently on a 🔥 Hot streak (last 10 days: 1.09 WHIP, 9.4 K/9) · "
                "Steamer: 162 K, 12 W, 1.21 WHIP projected"
            ),
            "score": 7.9,
            "categories_improved": ["k", "w", "whip"],
            "add_position": "SP",
            "add_streak": "🔥 Hot",
            "add_callup_note": "",
            "add_proj": {
                "proj_avg": None,
                "proj_ops": None,
                "proj_hr": None,
                "proj_sb": None,
                "proj_h": None,
                "proj_bb": None,
                "proj_k": 162.0,
                "proj_w": 12.0,
                "proj_sv_h": 0.0,
                "proj_whip": 1.21,
                "proj_k_bb": 3.4,
                "source": "Steamer",
            },
            "drop_position": "SP",
            "drop_streak": "❄️ Cold",
            "drop_proj": {
                "proj_avg": None,
                "proj_ops": None,
                "proj_hr": None,
                "proj_sb": None,
                "proj_h": None,
                "proj_bb": None,
                "proj_k": 98.0,
                "proj_w": 8.0,
                "proj_sv_h": 0.0,
                "proj_whip": 1.34,
                "proj_k_bb": 2.6,
                "source": "Steamer",
            },
            "matchup_context": "K: trailing (flippable) (gap 22)",
        },
    ],
    "matchup_summary": [
        {
            "category": "h",
            "my_value": 42.0,
            "opp_value": 38.0,
            "my_leads": True,
            "margin_pct": 0.105,
            "win_prob": 0.73,
            "status": "flippable_win",  # leading but not locked
        },
        {
            "category": "hr",
            "my_value": 8.0,
            "opp_value": 9.0,
            "my_leads": False,
            "margin_pct": 0.111,
            "win_prob": 0.38,
            "status": "flippable_loss",
        },
        {
            "category": "sb",
            "my_value": 3.0,
            "opp_value": 2.0,
            "my_leads": True,
            "margin_pct": 0.5,
            "win_prob": 0.85,
            "status": "safe_win",
        },
        {
            "category": "bb",
            "my_value": 15.0,
            "opp_value": 14.0,
            "my_leads": True,
            "margin_pct": 0.071,
            "win_prob": 0.62,
            "status": "flippable_win",
        },
        {
            "category": "fpct",
            "my_value": 0.987,
            "opp_value": 0.975,
            "my_leads": True,
            "margin_pct": 0.012,
            "win_prob": 0.68,
            "status": "toss_up",
        },
        {
            "category": "avg",
            "my_value": 0.278,
            "opp_value": 0.265,
            "my_leads": True,
            "margin_pct": 0.049,
            "win_prob": 0.61,
            "status": "flippable_win",
        },
        {
            "category": "ops",
            "my_value": 0.812,
            "opp_value": 0.798,
            "my_leads": True,
            "margin_pct": 0.018,
            "win_prob": 0.54,
            "status": "toss_up",
        },
        {
            "category": "w",
            "my_value": 3.0,
            "opp_value": 4.0,
            "my_leads": False,
            "margin_pct": 0.25,
            "win_prob": 0.22,
            "status": "safe_loss",
        },
        {
            "category": "k",
            "my_value": 28.0,
            "opp_value": 26.0,
            "my_leads": True,
            "margin_pct": 0.077,
            "win_prob": 0.65,
            "status": "flippable_win",
        },
        {
            "category": "whip",
            "my_value": 1.18,
            "opp_value": 1.24,
            "my_leads": True,
            "margin_pct": 0.048,
            "win_prob": 0.61,
            "status": "flippable_win",
        },
        {
            "category": "k_bb",
            "my_value": 3.2,
            "opp_value": 2.8,
            "my_leads": True,
            "margin_pct": 0.143,
            "win_prob": 0.74,
            "status": "flippable_win",
        },
        {
            "category": "sv_h",
            "my_value": 5.0,
            "opp_value": 7.0,
            "my_leads": False,
            "margin_pct": 0.286,
            "win_prob": 0.18,
            "status": "safe_loss",
        },
    ],
    "ip_pace": {
        "current_ip": 14.2,
        "projected_ip": 22.1,
        "min_ip": 21,
        "on_pace": True,
    },
    "callup_alerts": [
        {
            "player_id": "p_callup1",
            "player_name": "Jackson Chourio",
            "days_since_callup": 2,
            "team": "MIL",
            "from_level": "AAA",
        },
    ],
}

# ── Stub Roster DataFrame ──────────────────────────────────────────────────────

_ROSTER_ROWS: list[dict[str, object]] = [
    # Catchers
    {
        "slot": "C",
        "player_id": "p_realmuto",
        "player_name": "J.T. Realmuto",
        "team": "PHI",
        "position": "C",
        "h": 42,
        "hr": 8,
        "sb": 3,
        "bb": 15,
        "fpct": 0.987,
        "avg": 0.278,
        "ops": 0.812,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # First Base
    {
        "slot": "1B",
        "player_id": "p_goldschmidt",
        "player_name": "Paul Goldschmidt",
        "team": "STL",
        "position": "1B",
        "h": 38,
        "hr": 10,
        "sb": 1,
        "bb": 18,
        "fpct": 0.993,
        "avg": 0.271,
        "ops": 0.831,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # Second Base
    {
        "slot": "2B",
        "player_id": "p_edman",
        "player_name": "Tommy Edman",
        "team": "LAD",
        "position": "2B",
        "h": 31,
        "hr": 3,
        "sb": 7,
        "bb": 10,
        "fpct": 0.982,
        "avg": 0.259,
        "ops": 0.731,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # Third Base
    {
        "slot": "3B",
        "player_id": "p_devers",
        "player_name": "Rafael Devers",
        "team": "BOS",
        "position": "3B",
        "h": 40,
        "hr": 12,
        "sb": 0,
        "bb": 14,
        "fpct": 0.961,
        "avg": 0.284,
        "ops": 0.891,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # Shortstop
    {
        "slot": "SS",
        "player_id": "p_tatis",
        "player_name": "Fernando Tatis Jr.",
        "team": "SD",
        "position": "SS",
        "h": 36,
        "hr": 11,
        "sb": 8,
        "bb": 12,
        "fpct": 0.971,
        "avg": 0.268,
        "ops": 0.862,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # Outfielders
    {
        "slot": "OF1",
        "player_id": "p_judge",
        "player_name": "Aaron Judge",
        "team": "NYY",
        "position": "OF",
        "h": 35,
        "hr": 16,
        "sb": 1,
        "bb": 22,
        "fpct": 0.994,
        "avg": 0.291,
        "ops": 0.971,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    {
        "slot": "OF2",
        "player_id": "p_trout",
        "player_name": "Mike Trout",
        "team": "LAA",
        "position": "OF",
        "h": 29,
        "hr": 9,
        "sb": 2,
        "bb": 19,
        "fpct": 1.000,
        "avg": 0.274,
        "ops": 0.903,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    {
        "slot": "OF3",
        "player_id": "p_soto",
        "player_name": "Juan Soto",
        "team": "NYM",
        "position": "OF",
        "h": 33,
        "hr": 7,
        "sb": 2,
        "bb": 24,
        "fpct": 0.991,
        "avg": 0.282,
        "ops": 0.921,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # Utility
    {
        "slot": "Util1",
        "player_id": "p_betts",
        "player_name": "Mookie Betts",
        "team": "LAD",
        "position": "OF/2B",
        "h": 37,
        "hr": 9,
        "sb": 5,
        "bb": 16,
        "fpct": 0.989,
        "avg": 0.289,
        "ops": 0.881,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    {
        "slot": "Util2",
        "player_id": "p_acuna",
        "player_name": "Ronald Acuna Jr.",
        "team": "ATL",
        "position": "OF",
        "h": 32,
        "hr": 6,
        "sb": 9,
        "bb": 13,
        "fpct": 0.983,
        "avg": 0.271,
        "ops": 0.841,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # Starting Pitchers
    {
        "slot": "SP1",
        "player_id": "p_degrom",
        "player_name": "Jacob deGrom",
        "team": "TEX",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 3,
        "k": 28,
        "whip": 1.02,
        "k_bb": 4.1,
        "sv_h": None,
    },
    {
        "slot": "SP2",
        "player_id": "p_scherzer",
        "player_name": "Max Scherzer",
        "team": "NYM",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 2,
        "k": 24,
        "whip": 1.14,
        "k_bb": 3.8,
        "sv_h": None,
    },
    # Relief Pitchers
    {
        "slot": "RP1",
        "player_id": "p_hader",
        "player_name": "Josh Hader",
        "team": "HOU",
        "position": "RP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 0,
        "k": 12,
        "whip": 0.88,
        "k_bb": 5.2,
        "sv_h": 4,
    },
    {
        "slot": "RP2",
        "player_id": "p_clase",
        "player_name": "Emmanuel Clase",
        "team": "CLE",
        "position": "RP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 1,
        "k": 10,
        "whip": 0.91,
        "k_bb": 4.7,
        "sv_h": 3,
    },
    # Pitcher slots
    {
        "slot": "P1",
        "player_id": "p_gausman",
        "player_name": "Kevin Gausman",
        "team": "TOR",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 2,
        "k": 22,
        "whip": 1.19,
        "k_bb": 3.1,
        "sv_h": None,
    },
    {
        "slot": "P2",
        "player_id": "p_verlander",
        "player_name": "Justin Verlander",
        "team": "HOU",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 1,
        "k": 19,
        "whip": 1.28,
        "k_bb": 2.9,
        "sv_h": None,
    },
    # Bench players
    {
        "slot": "BN",
        "player_id": "p_bench1",
        "player_name": "Yordan Alvarez",
        "team": "HOU",
        "position": "OF/1B",
        "h": 28,
        "hr": 7,
        "sb": 0,
        "bb": 11,
        "fpct": 0.988,
        "avg": 0.261,
        "ops": 0.844,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    {
        "slot": "BN",
        "player_id": "p_bench2",
        "player_name": "Adley Rutschman",
        "team": "BAL",
        "position": "C",
        "h": 22,
        "hr": 4,
        "sb": 1,
        "bb": 13,
        "fpct": 0.994,
        "avg": 0.258,
        "ops": 0.791,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    {
        "slot": "BN",
        "player_id": "p_bench3",
        "player_name": "Tyler Glasnow",
        "team": "LAD",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 2,
        "k": 21,
        "whip": 1.08,
        "k_bb": 3.6,
        "sv_h": None,
    },
    {
        "slot": "BN",
        "player_id": "p_bench4",
        "player_name": "Jose Ramirez",
        "team": "CLE",
        "position": "3B",
        "h": 34,
        "hr": 8,
        "sb": 6,
        "bb": 12,
        "fpct": 0.974,
        "avg": 0.272,
        "ops": 0.853,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # IL slots
    {
        "slot": "IL",
        "player_id": "p_il1",
        "player_name": "Spencer Strider",
        "team": "ATL",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 0,
        "k": 4,
        "whip": 1.44,
        "k_bb": 2.8,
        "sv_h": None,
    },
    {
        "slot": "IL",
        "player_id": "p_il2",
        "player_name": "Shohei Ohtani",
        "team": "LAD",
        "position": "SP/OF",
        "h": 18,
        "hr": 5,
        "sb": 3,
        "bb": 8,
        "fpct": None,
        "avg": 0.294,
        "ops": 0.912,
        "w": 1,
        "k": 14,
        "whip": 1.11,
        "k_bb": 3.9,
        "sv_h": None,
    },
    # NA slots
    {
        "slot": "NA",
        "player_id": "p_na1",
        "player_name": "Luis Castillo",
        "team": "SEA",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 0,
        "k": 0,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    {
        "slot": "NA",
        "player_id": "p_na2",
        "player_name": "Corbin Carroll",
        "team": "ARI",
        "position": "OF",
        "h": 0,
        "hr": 0,
        "sb": 0,
        "bb": 0,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
    # IL slots (4 total; 2 more)
    {
        "slot": "IL",
        "player_id": "p_il3",
        "player_name": "Shane McClanahan",
        "team": "TB",
        "position": "SP",
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 0,
        "k": 2,
        "whip": 1.62,
        "k_bb": 2.1,
        "sv_h": None,
    },
    {
        "slot": "IL",
        "player_id": "p_il4",
        "player_name": "Trea Turner",
        "team": "PHI",
        "position": "SS",
        "h": 10,
        "hr": 1,
        "sb": 2,
        "bb": 4,
        "fpct": 0.968,
        "avg": 0.241,
        "ops": 0.694,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
    },
]

STUB_ROSTER_DF: pd.DataFrame = pd.DataFrame(_ROSTER_ROWS)

# Assign representative hot/cold labels for offline display
_ROSTER_STREAKS: dict[str, str] = {
    "p_judge": "🔥 Hot",
    "p_acuna": "🔥 Hot",
    "p_tatis": "🔥 Hot",
    "p_hader": "🔥 Hot",
    "p_il1": "❄️ Cold",
    "p_il3": "❄️ Cold",
    "p_verlander": "❄️ Cold",
    "p_bench3": "❄️ Cold",
}
STUB_ROSTER_DF["streak"] = STUB_ROSTER_DF["player_id"].map(
    lambda pid: _ROSTER_STREAKS.get(str(pid), "—")
)

# ── Stub Waiver Wire DataFrame ─────────────────────────────────────────────────

_WAIVER_ROWS: list[dict[str, object]] = [
    {
        "rank": 1,
        "player_id": "p_callup1",
        "player_name": "Jackson Chourio",
        "team": "MIL",
        "position": "OF",
        "score": 8.4,
        "h": 18,
        "hr": 4,
        "sb": 5,
        "bb": 7,
        "fpct": 0.981,
        "avg": 0.271,
        "ops": 0.792,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": True,
        "from_level": "AAA",
        "days_since_callup": 2,
    },
    {
        "rank": 2,
        "player_id": "p_wire2",
        "player_name": "Garrett Crochet",
        "team": "CWS",
        "position": "SP",
        "score": 7.9,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 2,
        "k": 31,
        "whip": 1.09,
        "k_bb": 3.4,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 3,
        "player_id": "p_wire3",
        "player_name": "Bryan Reynolds",
        "team": "PIT",
        "position": "OF",
        "score": 7.2,
        "h": 31,
        "hr": 6,
        "sb": 4,
        "bb": 10,
        "fpct": 0.986,
        "avg": 0.261,
        "ops": 0.779,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 4,
        "player_id": "p_wire4",
        "player_name": "Michael King",
        "team": "SD",
        "position": "SP/RP",
        "score": 6.8,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 1,
        "k": 24,
        "whip": 1.17,
        "k_bb": 3.1,
        "sv_h": 2,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 5,
        "player_id": "p_wire5",
        "player_name": "Pete Crow-Armstrong",
        "team": "CHC",
        "position": "OF",
        "score": 6.5,
        "h": 27,
        "hr": 3,
        "sb": 8,
        "bb": 8,
        "fpct": 0.992,
        "avg": 0.259,
        "ops": 0.748,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": True,
        "from_level": "AAA",
        "days_since_callup": 10,
    },
    {
        "rank": 6,
        "player_id": "p_wire6",
        "player_name": "Cristian Javier",
        "team": "HOU",
        "position": "SP",
        "score": 6.1,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 2,
        "k": 20,
        "whip": 1.22,
        "k_bb": 2.8,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 7,
        "player_id": "p_wire7",
        "player_name": "CJ Abrams",
        "team": "WSH",
        "position": "SS",
        "score": 5.9,
        "h": 29,
        "hr": 2,
        "sb": 9,
        "bb": 6,
        "fpct": 0.973,
        "avg": 0.248,
        "ops": 0.701,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 8,
        "player_id": "p_wire8",
        "player_name": "Ryan Pressly",
        "team": "HOU",
        "position": "RP",
        "score": 5.6,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 0,
        "k": 9,
        "whip": 1.01,
        "k_bb": 4.2,
        "sv_h": 3,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 9,
        "player_id": "p_wire9",
        "player_name": "Vinnie Pasquantino",
        "team": "KC",
        "position": "1B",
        "score": 5.3,
        "h": 26,
        "hr": 5,
        "sb": 0,
        "bb": 12,
        "fpct": 0.995,
        "avg": 0.256,
        "ops": 0.766,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 10,
        "player_id": "p_wire10",
        "player_name": "Ezequiel Tovar",
        "team": "COL",
        "position": "SS",
        "score": 5.0,
        "h": 24,
        "hr": 3,
        "sb": 6,
        "bb": 5,
        "fpct": 0.969,
        "avg": 0.252,
        "ops": 0.712,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 11,
        "player_id": "p_wire11",
        "player_name": "David Bednar",
        "team": "PIT",
        "position": "RP",
        "score": 4.8,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 0,
        "k": 11,
        "whip": 1.08,
        "k_bb": 3.8,
        "sv_h": 4,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 12,
        "player_id": "p_wire12",
        "player_name": "Ha-Seong Kim",
        "team": "SD",
        "position": "SS/2B",
        "score": 4.5,
        "h": 21,
        "hr": 2,
        "sb": 5,
        "bb": 9,
        "fpct": 0.977,
        "avg": 0.243,
        "ops": 0.689,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 13,
        "player_id": "p_wire13",
        "player_name": "Brandon Pfaadt",
        "team": "ARI",
        "position": "SP",
        "score": 4.3,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 1,
        "k": 17,
        "whip": 1.31,
        "k_bb": 2.5,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 14,
        "player_id": "p_wire14",
        "player_name": "Evan Carter",
        "team": "TEX",
        "position": "OF",
        "score": 4.1,
        "h": 19,
        "hr": 2,
        "sb": 3,
        "bb": 8,
        "fpct": 0.984,
        "avg": 0.247,
        "ops": 0.724,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": True,
        "from_level": "AA",
        "days_since_callup": 5,
    },
    {
        "rank": 15,
        "player_id": "p_wire15",
        "player_name": "Tarik Skubal",
        "team": "DET",
        "position": "SP",
        "score": 3.9,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 1,
        "k": 15,
        "whip": 1.38,
        "k_bb": 2.3,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 16,
        "player_id": "p_wire16",
        "player_name": "Austin Hays",
        "team": "PHI",
        "position": "OF",
        "score": 3.7,
        "h": 22,
        "hr": 3,
        "sb": 2,
        "bb": 6,
        "fpct": 0.979,
        "avg": 0.244,
        "ops": 0.711,
        "w": None,
        "k": None,
        "whip": None,
        "k_bb": None,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
    {
        "rank": 17,
        "player_id": "p_wire17",
        "player_name": "Zach Eflin",
        "team": "TB",
        "position": "SP",
        "score": 3.4,
        "h": None,
        "hr": None,
        "sb": None,
        "bb": None,
        "fpct": None,
        "avg": None,
        "ops": None,
        "w": 1,
        "k": 13,
        "whip": 1.42,
        "k_bb": 2.1,
        "sv_h": None,
        "callup": False,
        "from_level": None,
        "days_since_callup": None,
    },
]

STUB_WAIVER_DF: pd.DataFrame = pd.DataFrame(_WAIVER_ROWS)

_WAIVER_STREAKS: dict[str, str] = {
    "p_callup1": "🔥 Hot",
    "p_wire3": "🔥 Hot",
    "p_wire2": "🔥 Hot",
    "p_wire13": "❄️ Cold",
    "p_wire17": "❄️ Cold",
}
STUB_WAIVER_DF["streak"] = STUB_WAIVER_DF["player_id"].map(
    lambda pid: _WAIVER_STREAKS.get(str(pid), "—")
)

# ── Stub Transactions DataFrame ────────────────────────────────────────────

_TRANSACTION_ROWS: list[dict[str, object]] = [
    {
        "transaction_date": "2025-06-09",
        "type": "mlb_injury",
        "player_name": "Spencer Strider",
        "team": "ATL",
        "position": "SP",
        "notes": "Placed on 60-day IL (Tommy John surgery recovery)",
    },
    {
        "transaction_date": "2025-06-08",
        "type": "mlb_callup",
        "player_name": "Jackson Chourio",
        "team": "MIL",
        "position": "OF",
        "notes": "Called up from AAA Nashville",
    },
    {
        "transaction_date": "2025-06-07",
        "type": "mlb_activation",
        "player_name": "Ronald Acuna Jr.",
        "team": "ATL",
        "position": "OF",
        "notes": "Activated from 60-day IL (knee)",
    },
    {
        "transaction_date": "2025-06-06",
        "type": "mlb_callup",
        "player_name": "Pete Crow-Armstrong",
        "team": "CHC",
        "position": "OF",
        "notes": "Called up from AAA Iowa; optioned out Jun 3, recalled Jun 6",
    },
    {
        "transaction_date": "2025-06-05",
        "type": "mlb_injury",
        "player_name": "Shane McClanahan",
        "team": "TB",
        "position": "SP",
        "notes": "Placed on 15-day IL (shoulder inflammation)",
    },
    {
        "transaction_date": "2025-06-04",
        "type": "mlb_injury",
        "player_name": "Gerrit Cole",
        "team": "NYY",
        "position": "SP",
        "notes": "Placed on 15-day IL (elbow soreness); retroactive to Jun 2",
    },
    {
        "transaction_date": "2025-06-03",
        "type": "mlb_activation",
        "player_name": "Ozzie Albies",
        "team": "ATL",
        "position": "2B",
        "notes": "Activated from 10-day IL (wrist)",
    },
    {
        "transaction_date": "2025-06-02",
        "type": "mlb_injury",
        "player_name": "Luis Castillo",
        "team": "SEA",
        "position": "SP",
        "notes": "Placed on 15-day IL (right shoulder fatigue)",
    },
    {
        "transaction_date": "2025-06-01",
        "type": "mlb_callup",
        "player_name": "Evan Carter",
        "team": "TEX",
        "position": "OF",
        "notes": "Called up from AA Frisco",
    },
    {
        "transaction_date": "2025-05-30",
        "type": "mlb_demotion",
        "player_name": "Bobby Miller",
        "team": "LAD",
        "position": "SP",
        "notes": "Optioned to AAA Oklahoma City (roster crunch)",
    },
]

STUB_TRANSACTIONS_DF: pd.DataFrame = pd.DataFrame(_TRANSACTION_ROWS)

# ── Stub Trade Proposals ───────────────────────────────────────────────────

STUB_TRADES: list[dict[str, object]] = [
    {
        "give_player": "Kyle Tucker",
        "give_team": "HOU",
        "give_position": "OF",
        "give_helps": ["H", "HR", "SB"],
        "receive_player": "Bobby Witt Jr.",
        "receive_team": "KC",
        "receive_position": "SS",
        "receive_helps": ["H", "SB", "HR"],
        "my_category_gain": "+2.1 SB, +1.4 H/week",
        "rationale": "Tucker's elite SB upside fills your SB gap. Witt is a perennial "
        "top-5 SS who addresses your biggest category deficit.",
        "acceptance_pct": 68,
    },
    {
        "give_player": "Gerrit Cole",
        "give_team": "NYY",
        "give_position": "SP",
        "give_helps": ["K", "W", "WHIP"],
        "receive_player": "Aaron Judge",
        "receive_team": "NYY",
        "receive_position": "OF",
        "receive_helps": ["HR", "BB", "OPS"],
        "my_category_gain": "+3.8 HR, +1.2 BB/week",
        "rationale": "Cole is elite but your K/WHIP are already strong. Judge's "
        "power upgrades your worst categories: HR and OPS.",
        "acceptance_pct": 71,
    },
    {
        "give_player": "Josh Hader",
        "give_team": "HOU",
        "give_position": "RP",
        "give_helps": ["SV_H", "K/BB", "WHIP"],
        "receive_player": "Emmanuel Clase",
        "receive_team": "CLE",
        "receive_position": "RP",
        "receive_helps": ["SV_H", "WHIP", "K/BB"],
        "my_category_gain": "+1.3 SV+H, comparable ratios",
        "rationale": "Lateral RP swap sweetened with Clase's bullpen role security. "
        "Use the extra roster spot freed to add an OF hitter for H/SB.",
        "acceptance_pct": 55,
    },
]

# ── Stub News ───────────────────────────────────────────────────────────────

_NEWS_ROWS: list[dict[str, object]] = [
    {
        "id": "a1b2c3d4e5f60001",
        "player_id": "422.p.10897",
        "player_name": "Aaron Judge",
        "headline": "Aaron Judge crushes two home runs as Yankees rout Red Sox 11-2",
        "url": "https://example.com/judge-hr",
        "source": "MLB.com",
        "published_at": "2025-06-07 22:15:00",
        "sentiment_label": "Good",
        "sentiment_score": 0.6808,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60002",
        "player_id": "422.p.10897",
        "player_name": "Aaron Judge",
        "headline": "Judge discusses his approach at the plate this season",
        "url": "https://example.com/judge-interview",
        "source": "ESPN",
        "published_at": "2025-06-06 18:00:00",
        "sentiment_label": "Informative",
        "sentiment_score": 0.0,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60003",
        "player_id": "422.p.11477",
        "player_name": "Shohei Ohtani",
        "headline": "Ohtani goes 3-for-4 with a stolen base, extends hitting streak to 12",
        "url": "https://example.com/ohtani-streak",
        "source": "The Athletic",
        "published_at": "2025-06-07 23:45:00",
        "sentiment_label": "Good",
        "sentiment_score": 0.7351,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60004",
        "player_id": "422.p.9558",
        "player_name": "Spencer Strider",
        "headline": "Strider placed on 15-day IL with right elbow inflammation",
        "url": "https://example.com/strider-il",
        "source": "MLB.com",
        "published_at": "2025-06-07 14:30:00",
        "sentiment_label": "Bad",
        "sentiment_score": -0.6124,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60005",
        "player_id": "422.p.9558",
        "player_name": "Spencer Strider",
        "headline": "Braves cautious with Strider, MRI results pending",
        "url": "https://example.com/strider-mri",
        "source": "Rotowire",
        "published_at": "2025-06-07 20:10:00",
        "sentiment_label": "Bad",
        "sentiment_score": -0.4215,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60006",
        "player_id": "422.p.10660",
        "player_name": "Yordan Alvarez",
        "headline": "Alvarez named AL Player of the Week after .450 average, 3 HR",
        "url": "https://example.com/alvarez-potw",
        "source": "MLB.com",
        "published_at": "2025-06-07 12:00:00",
        "sentiment_label": "Good",
        "sentiment_score": 0.8126,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60007",
        "player_id": "422.p.11117",
        "player_name": "Freddie Freeman",
        "headline": "Freeman day-to-day with minor ankle soreness, not expected to miss time",
        "url": "https://example.com/freeman-ankle",
        "source": "Dodgers PR",
        "published_at": "2025-06-06 16:45:00",
        "sentiment_label": "Informative",
        "sentiment_score": -0.0258,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60008",
        "player_id": "422.p.12345",
        "player_name": "Gerrit Cole",
        "headline": "Cole fans 12, allows 1 run over 7 innings in dominant start",
        "url": "https://example.com/cole-dominant",
        "source": "Yankees.com",
        "published_at": "2025-06-05 23:00:00",
        "sentiment_label": "Good",
        "sentiment_score": 0.5994,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60009",
        "player_id": "422.p.8967",
        "player_name": "Jose Ramirez",
        "headline": "Ramirez hits walk-off single to complete dramatic comeback win",
        "url": "https://example.com/ramirez-walkoff",
        "source": "ESPN",
        "published_at": "2025-06-07 21:55:00",
        "sentiment_label": "Good",
        "sentiment_score": 0.7717,
        "fetched_at": "2025-06-08 09:00:00",
    },
    {
        "id": "a1b2c3d4e5f60010",
        "player_id": "422.p.7654",
        "player_name": "Julio Rodriguez",
        "headline": "Rodriguez in a 1-for-18 slump, Mariners give him a rest day",
        "url": "https://example.com/jrod-slump",
        "source": "Seattle Times",
        "published_at": "2025-06-06 19:20:00",
        "sentiment_label": "Bad",
        "sentiment_score": -0.3612,
        "fetched_at": "2025-06-08 09:00:00",
    },
]

STUB_NEWS_DF: pd.DataFrame = pd.DataFrame(_NEWS_ROWS)
